# Site wide configuration

title:            Not rude but honest
locale:           en_US
url:


# Jekyll configuration

permalink:         /:year/:month/:title/
markdown:          kramdown
highlighter:       rouge
excerpt_separator: ""
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

# Site owner
owner:
  name: Corinna and Robert
  avatar: bio-photo.jpg
  bio: ""
  disqus-shortname: "notrudebuthonestcom"

author_names:
  - corinna
  - robert

authors:
  corinna:
    name: Corinna Wiesner
    avatar: bio-photo-corinna.jpg
    bio: "Software Developer"
    twitter: walkertowski
    github: corinnawiesner
    linkedin: corinnawiesner
    xing: Corinna_Wiesner4
  robert:
    name: Robert Gogolok
    avatar: bio-photo-robert.jpg
    bio: "Software Engineer and Dad"
    twitter: gogolok
    github: gogolok
    linkedin: robertgogolok
    xing: Robert_Gogolok


include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

tag_page_layout: tag_page
tag_page_dir: tag
